
#Assignment1 (abedalaziz khalaf)
# Question 1 (a)
name=input("Enter your Name:")
print("Welcom",name)
number1= float(input("Enter your 1st number:"))
number2= float(input("Enter your 2nd number:"))
Sum1=float(number1 +5)
Sum2=float(number2 +5)
Sub1=float(number1 -5)
Sub2=float(number2 -5)
Mul1=float(number1 *5)
Mul2=float(number2 *5)
Div1=float(number1 /5)
Div2=float(number2 /5)
Rem1=float(number1 %5)
Rem2=float(number2 %5)
Ex1= float(number1**5)
Ex2= float(number2**5)
print("\"5 + your 1st number:\"", Sum1)
print("\"5 + your 2nd number:\"", Sum2)
print("\"5 - your 1st number:\"", Sub1)
print("\"5 - your 2nd number:\"", Sub2)
print("\"5 * your 1st number:\"", Mul1)
print("\"5 * your 2nd number:\"", Mul2)
print("\"5 / your 1st number:\"", Div1)
print("\"5 / your 2nd number:\"", Div2)
print("the reminder of", number1, "over 5:", Rem1)
print("the reminder of", number2, "over 5:", Rem2)
print("the exponent of", number1, "is:", Ex1)
print("the exponent of", number2, "is:", Ex2)
